apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-cluster-deployment-the-island
  namespace: ark-orchestrator
spec:
  selector:
    matchLabels:
      app: ark-cluster-deployment-the-island
  serviceName: ark-cluster-deployment-the-island
  replicas: 1
  template:
    metadata:
      labels:
        app: ark-cluster-deployment-the-island
    spec:
      containers:
        - name: runner
          image: ghcr.io/danussi/ark-orchestrator-arkmanager:main
          command: ["/bin/bash", "/scripts/start.sh"]
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "/scripts/stop.sh"]
          ports:
            - containerPort: 27015
              name: query
              protocol: UDP
            - containerPort: 27020
              name: rcon
              protocol: TCP
            - containerPort: 7777
              name: game
              protocol: UDP
            - containerPort: 7778
              name: raw
              protocol: UDP
          volumeMounts:
            - mountPath: /data
              name: ark-cluster-storage
            - mountPath: /scripts
              name: ark-cluster-scripts
      volumes:
        - name: ark-cluster-storage
          persistentVolumeClaim:
            claimName: ark-cluster-storage
        - name: ark-cluster-scripts
          configMap:
            name: ark-cluster-scripts
            optional: false
            defaultMode: 0777