apiVersion: v1
kind: Service
metadata:
  name: ark-nexus-aberration
  namespace: ark-orchestrator
spec:
  type: LoadBalancer
  selector:
    app: ark-nexus-aberration
  ports:
    - port: 27015
      name: query
      protocol: UDP
    - port: 27020
      name: rcon
      protocol: TCP
    - port: 7777
      name: game
      protocol: UDP
    - port: 7778
      name: raw
      protocol: UDP
